# Generated by Django 3.2.9 on 2021-11-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirCraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('a_status', models.IntegerField(choices=[(0, 'operational'), (1, 'under maintenance'), (2, 'suspended')], default=0)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('run_c', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(choices=[('A', 'Air traffic control'), ('M', 'Maintenance'), ('E', 'Emergency crew'), ('S', 'Security')], max_length=1)),
                ('ap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField()),
                ('fl_status', models.CharField(choices=[('S', 'Scheduled'), ('A', 'Active'), ('L', 'Landed'), ('C', 'Cancelled')], default='S', max_length=1)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('d_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airflow.department')),
                ('super', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airflow.employee')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='d_head_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.employee'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_n', models.IntegerField()),
                ('total_fare', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Confirmed'), (1, 'Pending')], default=1)),
                ('fl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.flight')),
                ('ps_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='ap_m_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.employee'),
        ),
    ]
