# Generated by Django 3.2.9 on 2021-11-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
