# Generated by Django 3.2.9 on 2021-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0002_auto_20211110_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='d_name',
            field=models.CharField(choices=[('A', 'Air traffic control'), ('S', 'Security')], max_length=1),
        ),
    ]
