# Generated by Django 3.2.9 on 2021-11-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0003_auto_20211111_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='age',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
