# Generated by Django 3.2.9 on 2021-11-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0006_auto_20211111_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=30, null=True)),
                ('dep_time', models.DateTimeField()),
                ('arr_time', models.DateTimeField()),
                ('fare', models.IntegerField()),
                ('fl_status', models.CharField(choices=[('S', 'Scheduled'), ('A', 'Active'), ('L', 'Landed'), ('C', 'Cancelled')], default='S', max_length=1)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.aircraft')),
                ('arr_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arr_airport', to='airflow.airport')),
                ('dep_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_airport', to='airflow.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_n', models.IntegerField()),
                ('total_fare', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Confirmed'), (1, 'Pending')], default=1)),
                ('fl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.flight')),
                ('ps_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.passenger')),
            ],
        ),
    ]
