# Generated by Django 3.2.9 on 2021-11-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0007_booking_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='a_id',
            new_name='aircraft',
        ),
    ]
