# Generated by Django 3.2.9 on 2021-11-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0008_rename_a_id_flight_aircraft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
