# Generated by Django 3.2.9 on 2021-11-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0010_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_key', models.CharField(max_length=20)),
            ],
        ),
    ]
