# Generated by Django 3.2.9 on 2021-11-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0011_adminkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminKey',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='ap_m_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='fl_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='super',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arr_airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='dep_airport',
        ),
        migrations.DeleteModel(
            name='AirCraft',
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
