# Generated by Django 3.2.9 on 2021-11-13 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airflow', '0012_auto_20211113_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_key', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AirCraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('a_status', models.IntegerField(choices=[(0, 'operational'), (1, 'under maintenance'), (2, 'suspended')], default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('run_c', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CongestionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_time', models.DateTimeField()),
                ('arr_time', models.DateTimeField()),
                ('fare', models.IntegerField()),
                ('fl_status', models.CharField(choices=[('S', 'Scheduled'), ('A', 'Active'), ('L', 'Landed'), ('C', 'Cancelled')], default='S', max_length=1)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.airline')),
                ('arr_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arr_airport', to='airflow.airport')),
                ('dep_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_airport', to='airflow.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_n', models.IntegerField()),
                ('total_fare', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Confirmed'), (1, 'Pending')], default=0)),
                ('fl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airflow.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
