# Generated by Django 3.2.9 on 2021-11-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0013_adminkey_aircraft_airline_airport_booking_congestionindex_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congestionindex',
            name='delta',
            field=models.DurationField(),
        ),
    ]
